package com.esraa.myAppwithDocker.model;

import java.io.Serializable;
import java.util.Objects;

import org.hibernate.annotations.GeneratorType;
import org.hibernate.annotations.ValueGenerationType;

import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import lombok.Data;

@Entity
@Table(name="products")
@Data
public class Product implements Serializable{

	@Id
	Integer id ;
	
	String name ;
	
	Double price ;
	
	
	@Override
	public boolean equals(Object obj) {
		
		
		if(this==obj) return true ; // the same object 
		
		if(obj==null || getClass() != obj.getClass() ) return false ;
		
		Product other = (Product) obj ;
		
		return this.name == other.name && this.price == other.price ;
			
		
	}
	
	// need to overrride hashcode 
	 @Override
	    public int hashCode() {
	        return Objects.hash(name, price);
	    }
	//hashCode() returns an integer value, generated by a hashing algorithm.

    //Objects that are equal (according to their equals()) must return the same hash code.
	 //Different objects do not need to return different hash codes.
	
	
}
