package com.esraa.myAppwithDocker.model;

import java.io.Serializable;
import java.util.Objects;

import org.hibernate.annotations.GeneratorType;
import org.hibernate.annotations.ValueGenerationType;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import jakarta.persistence.Transient;
import lombok.Data;

@Entity
@Table(name="products")
@Data
@JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
public class Product implements  Serializable {

	@Id
	Integer id ;
	
	
	//@Transient
	String name ;
	
	
	//@JsonIgnore
	 Double price ;
	
	//transient Double price ;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "category_id")
	Category category;
	

	@Override
	public boolean equals(Object obj) {
		
		
		if(this==obj) return true ; // the same object 
		
		if(obj==null || getClass() != obj.getClass() ) return false ;
		
		Product other = (Product) obj ;
		
		return this.name == other.name && this.price == other.price ;
			
		
	}
	
	
	@Override
	public String toString() {
		
		return " id = " + this.id + 
				"name = " + this.name + 
				"price = "  +  this.price   ;
		
		
	}
	
	// need to overrride hashcode 
	 @Override
	    public int hashCode() {
	        return Objects.hash(name, price);
	    }
	//hashCode() returns an integer value, generated by a hashing algorithm.

    //Objects that are equal (according to their equals()) must return the same hash code.
	 //Different objects do not need to return different hash codes.
	
	
}
